import type { Metadata } from "next"
import localFont from "next/font/local"
import { Suspense } from "react"
import { Toaster } from "sonner"
import { ApolloWrapper } from "./apollo-wrapper"
import { CheckMagicLink } from "./check-magic-link"
import "./globals.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Floweden App",
  description: "Generated by create floweden",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ApolloWrapper>
          {children}
          <Suspense>
            <CheckMagicLink />
          </Suspense>
        </ApolloWrapper>
        <Toaster />
      </body>
    </html>
  )
}
